encoding: utf-8

# SEO相关信息
title: AYue Blog
description: AYue的个人博客
keywords: AYue,Blog,Java,Html,JavaScript
author: AYue
footerText: 'Copyright © 2019 AYue的个人博客'

# 路径配置
domainUrl: 'https://yuexiansheng1.github.io/blog'
baseUrl: ''

# 菜单
menu:
  - title: Home
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: Links
    url: /pages/links.html
  - title: Chat
    url: /pages/chat.html
  - title: About
    url: /pages/about.html

# 文章url前缀，固定格式，不要动
permalink: /posts/:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  input: GFM

exclude: ["CNAME", "README.md", "build-tool"]